### ISSUE TITLE
Unfortunate typo in example

### ISSUE THREAD

**Issue by olivier-fs** [kamchatka-volcano/fcgi_responder#9]
Hi!
Nice library (and maintained unlike the others)

I have hit a small issue when testing fcgi_responder.
I have slightly modified the sample code to use TCP sockets (nginx-1.25.2 on Windows platform, so no AF_UNIX sockets).
But the example code has an extra space at the end of the status response header:
```
response.setData("HTTP/1.1 200 OK\r\n "    <==== EXTRA-SPACE !
                         "Content-Type: text/html\r\n"
```
nginx chokes with 502 Bad Gateway.
Removing the extra-space makes nginx happy
Very unfortunate typo that makes it seem at first sight that the lib doesn't work... Hopefully it's very easy to fix.

Regards.

**Comment by olivier-fs** [comment]
More:

nginx fastcgi module accepts "HTTP/1.1 200 0K", but Apache mod_proxy_fcgi wants "Status: 200 0K".

With "HTTP/1.1 200 0K" I get this :

- with curl
```
$ curl -v http://127.0.0.1:8080/fcgi/test
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080
> GET /fcgi/test HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/8.3.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Thu, 28 Sep 2023 15:23:59 GMT
< Server: Apache/2.4.57 (Win64)
< Content-Length: 0
< Connection: close
<
* Closing connection
```

- in httpd error.log:
```
[Thu Sep 28 17:23:52.395810 2023] [proxy_fcgi:error] [pid 10380:tid 1208] [client 127.0.0.1:64663] AH01070: Error parsing script headers
[Thu Sep 28 17:23:52.395810 2023] [proxy_fcgi:error] [pid 10380:tid 1208] (22)Invalid argument: [client 127.0.0.1:64663] AH01075: Error dispatching request to :8080:
[Thu Sep 28 17:23:59.006909 2023] [proxy_fcgi:error] [pid 10380:tid 1208] [client 127.0.0.1:64680] malformed header from script 'test': Bad header:
```

The CGI Specification (section-6.3.3.  Status) says "Status".
nginx is clever but disrespectful of the RFC...

Again, easy to fix the sample code,

Regards

**Comment by kamchatka-volcano** [comment]
Thanks for reporting it! I'll try to fix it ASAP. 

Ideally, I should create cross-platform examples for `fcgi_responder` and test them on CI, but this seems like redundant work since `fcgi_responder` is used in [asyncgi](https://github.com/kamchatka-volcano/asyncgi), which already has cross-platform functional tests.  Maybe someday I'll find the willpower for that)

**Comment by kamchatka-volcano** [comment]
Fixed examples on `master`
